language: ruby
cache: bundler

sudo: false
# Early warning system to catch if Rubygems breaks something
before_install:
  # the new 2.5.0 rubygems is busted with 1.7.6 bundler, the
  # new 1.10.6 bundler is busted with our rake tasks.  the
  # 2.4.5 rubygems with 1.7.6 bundler in travis currently works.
  # see https://github.com/bundler/bundler/issues/3982
#  gem update --system

branches:
  only:
  - master
  - 10-stable
  - 11-stable

# do not run expensive spec tests on PRs, only on branches
script: "
echo '--color\n-fp' > .rspec;
sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers;
sudo -E $(which bundle) exec rake spec;
"

env:
  global:
    - FORCE_FFI_YAJL=ext

matrix:
  include:
  - rvm: rbx
    sudo: true
  - rvm: 2.2
    sudo: required
    dist: trusty
    cache:
    before_install:
      - sudo apt-get update
      - sudo apt-get -y install squid3 git
    env:
      global:
        - PROXY_TESTS_DIR=proxy_tests/files/default/scripts
        - PROXY_TESTS_REPO=$PROXY_TESTS_DIR/repo
    script:
      - sudo rm -rf /usr/bin/knife /usr/bin/chef-client # get rid of these pre-installed ones
      - bundle env
      - bundle exec chef-client --version
      - git clone -b tball/knife_tests https://github.com/chef/proxy_tests.git
      - rvmsudo bundle exec bash $PROXY_TESTS_DIR/run_tests.sh chef_client \* \* /tmp/out.txt
    after_script:
      - cat /tmp/out.txt
      - sudo cat /var/log/squid3/cache.log
      - sudo cat /var/log/squid3/access.log

  allow_failures:
    - rvm: rbx
notifications:
  on_change: true
  on_failure: true
  on_success: change
  on_pull_requests: false
  irc:
    channels:
    - chat.freenode.net#chef-hacking
  webhooks:
    urls:
    # Gitter IM
    - secure: HmMKr/ysKVyKUJ24PRCHcA8QCmlFoukrYumY0GRLzvaFWO8PknHO1t/0RbrKRb2ed/hgkFd+RKNCYvSvcE8Ahr2vlMrBeGHGfVeOGkWtbhLgNqo1b50Ll9CqvTM8X2ZIq6hIWraanwoYRQu/8uGL29yH4lBi7DhpTkFwBMLulhQ=
  hipchat:
    rooms:
    # Build Statuses
    - secure: G8MNo94L8bmWWwkH2/ViB2QaZnZHZscYM/mEjDbOGd15sqrruwckeARyBoUcRI7P1C6AFmS4IKCNVXa6KzX4Pbh51gQWM92zRpRTZpplwtXz53/1l8ajLFLLMLvEMTlBFAANUKEUFAQPY4dMa14V3Qc5oijfIncN61k4nZNTKpY=
    # Open Source
    - secure: hmcex4PpG5dn8WvjndONO4xCUKOC5kPU/bUEGRrfVbe2YKJE7t0XXbNDC96W/xBgzgnJzvf1Er0zJKDrNf4qEDEWFoozdN00WLcqREgaLLS3Seto2FjR/BpBk5q+sCV0rwwEMms2P4Qk+VSnDCnm9EaeM55hOabqNuOrRzoZLBQ=
